Following [Pomegranate tutorial](https://pomegranate.readthedocs.io/en/latest/tutorials/B_Model_Tutorial_4_Hidden_Markov_Models.html)

In [1]:
import numpy as np
import torch
from pomegranate import *
# from matplotlib import pyplot as plt

/home/tom/miniconda3/envs/SAGAconf/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
sequence = 'CGACTACTGACTACTCGCCGACGCGACTGCCGTCTATACTGCGCATACGGC'
X = np.array([[[['A', 'C', 'G', 'T'].index(char)] for char in sequence]])
print("X: ", X.shape)
print(X)

X:  (1, 51, 1)
[[[1]
  [2]
  [0]
  [1]
  [3]
  [0]
  [1]
  [3]
  [2]
  [0]
  [1]
  [3]
  [0]
  [1]
  [3]
  [1]
  [2]
  [1]
  [1]
  [2]
  [0]
  [1]
  [2]
  [1]
  [2]
  [0]
  [1]
  [3]
  [2]
  [1]
  [1]
  [2]
  [3]
  [1]
  [3]
  [0]
  [3]
  [0]
  [1]
  [3]
  [2]
  [1]
  [2]
  [1]
  [0]
  [3]
  [0]
  [1]
  [2]
  [2]
  [1]]]


In [3]:
SEQ_LEN = 20

Deviations

In [4]:
devs = 5 * torch.rand(1, SEQ_LEN)
devs

tensor([[0.0758, 0.8415, 0.8249, 4.1123, 2.7568, 1.6167, 2.4916, 1.0518, 3.4067,
         2.7360, 2.9641, 0.5943, 2.7017, 2.8463, 0.3534, 3.4694, 3.5917, 2.7192,
         3.4238, 1.1663]])

Means

In [34]:
means = 100 * (torch.rand(SEQ_LEN, 1).reshape(SEQ_LEN))
means

tensor([88.9594,  4.7539,  3.7568, 53.8699, 64.6707, 40.4535, 34.5336,  4.6358,
        12.7373,  2.8778, 99.6916, 48.6602, 79.5351, 63.9598, 83.2718, 66.0755,
        89.7949, 76.1114, 37.9539, 17.8313])

In [35]:
h3k4me3 = torch.normal(means, devs)
h3k4me3

tensor([ 89.5434,   4.3574,   0.6843,  54.0890,  65.0644,  40.7016,  33.6917,
         -3.0840,  15.9637,   2.9518, 100.9461,  41.2846,  76.4859,  63.9647,
         83.3161,  69.3621,  86.1599,  70.0809,  40.4581,  16.7364])

In [39]:
from pomegranate.distributions import Normal
from pomegranate.hmm import DenseHMM
hmm = DenseHMM([Normal()] * SEQ_LEN, verbose=True)
hmm

DenseHMM(
  (start): Silent()
  (end): Silent()
)

In [42]:
hmm.fit(h3k4me3)
for node in hmm.distributions:
    print(node)

ValueError: Parameter X must have 2 dims

In [36]:
all_tracks = torch.distributions.MultivariateNormal(means, torch.diag(devs))
all_tracks.sample()

tensor([88.1742,  4.9616,  0.9904, 52.9784, 65.4905, 39.1773, 33.9875,  5.6228,
        12.1969,  2.4487, 99.3737, 49.7558, 77.5732, 63.9789, 83.7520, 64.0095,
        89.4957, 68.7929, 37.9740, 18.1841])