In [2]:
import torch
big_tab = torch.empty((10, 3))
big_tab

/home/tom/miniconda3/envs/SAGAconf/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[ 8.3899e-03,  4.5668e-41,  2.0777e+31],
        [ 1.7652e+22,  1.2849e-02,  4.5668e-41],
        [ 8.3901e-03,  4.5668e-41, -1.5919e+23],
        [ 1.5067e+05,  1.2860e-02,  4.5668e-41],
        [ 8.3902e-03,  4.5668e-41,  1.8226e+01],
        [ 1.7361e+19,  1.2860e-02,  4.5668e-41],
        [ 8.3903e-03,  4.5668e-41,  1.6511e-35],
        [-4.7173e+14,  1.2850e-02,  4.5668e-41],
        [ 8.3455e-03,  4.5668e-41,  6.0749e-37],
        [ 5.1106e+25,  1.2861e-02,  4.5668e-41]])

In [3]:
big_tab.shape[0]

10

In [4]:

for i in range(big_tab.shape[0]):
    big_tab[i] = torch.tensor([i+1, i, i-1])
print(big_tab)

tensor([[ 1.,  0., -1.],
        [ 2.,  1.,  0.],
        [ 3.,  2.,  1.],
        [ 4.,  3.,  2.],
        [ 5.,  4.,  3.],
        [ 6.,  5.,  4.],
        [ 7.,  6.,  5.],
        [ 8.,  7.,  6.],
        [ 9.,  8.,  7.],
        [10.,  9.,  8.]])


In [5]:


for i in range(big_tab.shape[0]):
    big_tab[i] = torch.tensor([i+1, i, i-1])
print(big_tab)

tensor([[ 1.,  0., -1.],
        [ 2.,  1.,  0.],
        [ 3.,  2.,  1.],
        [ 4.,  3.,  2.],
        [ 5.,  4.,  3.],
        [ 6.,  5.,  4.],
        [ 7.,  6.,  5.],
        [ 8.,  7.,  6.],
        [ 9.,  8.,  7.],
        [10.,  9.,  8.]])


In [6]:
tab_arr = big_tab.numpy()
tab_arr.mean(axis=0)

array([5.5, 4.5, 3.5], dtype=float32)

In [7]:
tab_arr.mean(axis=1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [3]:

import numpy as np
from pyBedGraph import BedGraph
import pyBigWig
from pathlib import Path

In [4]:
DATA_DIR = Path().resolve().parent.parent / "data"
SIZES_FILE_PATH = DATA_DIR / "hg38.chrom.sizes"

In [10]:
import sys
BW_FILE_PATH = DATA_DIR / "CD14-positive monocyte" / "H2AFZ" / "ENCFF834IMH.bigWig"
print(BW_FILE_PATH.is_file())
bw_k27 = pyBigWig.open(str(BW_FILE_PATH.absolute()))
print(type(bw_k27))
print(sys.getsizeof(bw_k27))

True
<class 'pyBigWig.bigWigFile'>
48


In [14]:
bw_k27.values("chr4", 0, 1000000, numpy=True).sum()

561367.9

In [12]:
import pandas as pd
chrom_sizes = pd.read_csv(SIZES_FILE_PATH, sep="\t", header=None, names=["name", "size"])
for row in chrom_sizes.itertuples():
    print(row[1:])

('chr1', 248956422)
('chr2', 242193529)
('chr3', 198295559)
('chr4', 190214555)
('chr5', 181538259)
('chr6', 170805979)
('chr7', 159345973)
('chrX', 156040895)
('chr8', 145138636)
('chr9', 138394717)
('chr11', 135086622)
('chr10', 133797422)
('chr12', 133275309)
('chr13', 114364328)
('chr14', 107043718)
('chr15', 101991189)
('chr16', 90338345)
('chr17', 83257441)
('chr18', 80373285)
('chr20', 64444167)
('chr19', 58617616)
('chrY', 57227415)
('chr22', 50818468)
('chr21', 46709983)
('chr15_KI270905v1_alt', 5161414)
('chr6_GL000256v2_alt', 4929269)
('chr6_GL000254v2_alt', 4827813)
('chr6_GL000251v2_alt', 4795265)
('chr6_GL000253v2_alt', 4677643)
('chr6_GL000250v2_alt', 4672374)
('chr6_GL000255v2_alt', 4606388)
('chr6_GL000252v2_alt', 4604811)
('chr17_KI270857v1_alt', 2877074)
('chr16_KI270853v1_alt', 2659700)
('chr16_KI270728v1_random', 1872759)
('chr17_GL000258v2_alt', 1821992)
('chr5_GL339449v2_alt', 1612928)
('chr14_KI270847v1_alt', 1511111)
('chr17_KI270908v1_alt', 1423190)
('chr14_KI